package signing

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"

	"homebase/internal/types"
)

// Signer uses Ed25519 cryptography to physically prove that what the LLM
// claimed it would do is exactly what the engine executed.
type Signer struct {
	privateKey ed25519.PrivateKey
	publicKey  ed25519.PublicKey
}

// NewSigner initializes the cryptographic layer. In production, this private key
// is held by the execution engine, NOT the LLM.
func NewSigner(privateKey ed25519.PrivateKey) *Signer {
	return &Signer{
		privateKey: privateKey,
		publicKey:  privateKey.Public().(ed25519.PublicKey),
	}
}

// SignDecision seals the decision. If the LLM tries to silently alter the plan
// during execution, the signature will be rendered mathematically invalid.
func (s *Signer) SignDecision(decision types.AssuranceCase) (types.DSSEEnvelope, error) {
	// We hash the exact plan the LLM submitted, combined with the hard evidence
	// generated by the Sandbox (not the LLM's summary of the evidence).
	payload := fmt.Sprintf("%s|%s|%s|%s", decision.ID(), decision.Claim(), decision.Argument(), decision.Evidence())

	hash := sha256.Sum256([]byte(payload))
	sigBytes := ed25519.Sign(s.privateKey, hash[:])

	sigHex := hex.EncodeToString(sigBytes)
	sig := types.NewDSSESignature("homebase-ed25519", sigHex)

	// Since we are mocking the DSSE base64 payload requirement to match schema
	return types.NewDSSEEnvelope("eyJwYXlsb2FkIjoiYmFzZTY0In0=", decision, sig), nil
}

// Verify ensures the signature perfectly matches the payload.
// This fulfills Invariant 4 (Integrity).
func (s *Signer) Verify(envelope types.DSSEEnvelope) error {
	decision := envelope.DecodedPayload()
	payload := fmt.Sprintf("%s|%s|%s|%s", decision.ID(), decision.Claim(), decision.Argument(), decision.Evidence())
	hash := sha256.Sum256([]byte(payload))

	// In a real DSSE, we would verify all signatures or a specific one. Here we verify the first.
	if len(envelope.Signatures()) == 0 {
		return errors.New("no signatures present in envelope")
	}

	sigBytes, err := hex.DecodeString(envelope.Signatures()[0].Sig())
	if err != nil {
		return errors.New("invalid signature encoding")
	}

	if !ed25519.Verify(s.publicKey, hash[:], sigBytes) {
		return errors.New("CRITICAL: Signature verification failed. The LLM or a rogue process tampered with the plan.")
	}

	return nil
}
