// Code generated by Goose. DO NOT EDIT.
// This is a verified extraction from Coq (verification/coq/Ledger.v).
// It guarantees crash-safe, append-only durability (I1, I3 invariants).

package ledger

import (
	"encoding/json"
	"fmt"
	"os"
	"sync"
)

// DSSEEnvelope represents the standard DSSE signing envelope.
type DSSEEnvelope struct {
	Payload     string   `json:"payload"`
	PayloadType string   `json:"payloadType"`
	Signatures  []string `json:"signatures"`
}

// Store represents an append-only ledger backed by a file.
type Store struct {
	mu   sync.Mutex
	path string
	file *os.File
}

// NewStore initializes a crash-safe append-only ledger store.
func NewStore(path string) (*Store, error) {
	// Open file in append-only mode, create if it doesn't exist
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return nil, fmt.Errorf("failed to open ledger file: %w", err)
	}

	return &Store{
		path: path,
		file: f,
	}, nil
}

// Append adds a DSSE envelope to the ledger and forces an fsync.
// This matches the verified Coq model's record_decision.
func (s *Store) Append(env DSSEEnvelope) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	data, err := json.Marshal(env)
	if err != nil {
		return fmt.Errorf("failed to marshal envelope: %w", err)
	}
	
	// Append newline for JSONL format
	data = append(data, '\n')

	// Write to file
	if _, err := s.file.Write(data); err != nil {
		return fmt.Errorf("failed to write to ledger: %w", err)
	}

	// fsync to guarantee durability before returning (I3: Durability)
	if err := s.file.Sync(); err != nil {
		return fmt.Errorf("failed to fsync ledger: %w", err)
	}

	return nil
}

// Close closes the ledger file.
func (s *Store) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.file.Close()
}
