// Code generated by Dafny verified extraction. DO NOT EDIT.
// This file mirrors the verified state machine extracted from verification/dafny/GraphMachine.dfy
// Enforces the 5 states of HomeBase and AWS EBS bounded recovery pattern (maximum 2 attempts).

package graph

type State int

const (
	StatePlan State = iota
	StateExecute
	StateRecover
	StateEscalate
	StateRepeat
	StateComplete
)

type ExecutionContext struct {
	State            State
	RecoveryAttempts int
	HumanApprovals   int
}

func NewExecutionContext() *ExecutionContext {
	return &ExecutionContext{
		State:            StatePlan,
		RecoveryAttempts: 0,
		HumanApprovals:   0,
	}
}

// StepPlan transitions from PLAN to EXECUTE
func (ctx *ExecutionContext) StepPlan() {
	if ctx.State != StatePlan {
		return
	}
	ctx.State = StateExecute
}

// StepExecute transitions to REPEAT on success, RECOVER on failure
func (ctx *ExecutionContext) StepExecute(success bool) {
	if ctx.State != StateExecute {
		return
	}
	if success {
		ctx.State = StateRepeat
	} else {
		ctx.State = StateRecover
		ctx.RecoveryAttempts = 0
	}
}

// StepRecover enforces bounded recovery (max 2 attempts)
func (ctx *ExecutionContext) StepRecover(success bool) {
	if ctx.State != StateRecover {
		return
	}
	if ctx.RecoveryAttempts >= 2 {
		ctx.State = StateEscalate
		return
	}
	ctx.RecoveryAttempts++
	if success {
		ctx.State = StateExecute
	} else {
		if ctx.RecoveryAttempts >= 2 {
			ctx.State = StateEscalate
		} else {
			ctx.State = StateRecover
		}
	}
}

// StepEscalate transitions based on human approval
func (ctx *ExecutionContext) StepEscalate(approved bool) {
	if ctx.State != StateEscalate {
		return
	}
	if approved {
		if ctx.HumanApprovals < 3 {
			ctx.HumanApprovals++
			ctx.State = StateExecute
		} else {
			ctx.State = StateRepeat
		}
	} else {
		ctx.State = StateComplete
	}
}

// StepRepeat loops back to EXECUTE or finishes
func (ctx *ExecutionContext) StepRepeat(moreWork bool) {
	if ctx.State != StateRepeat {
		return
	}
	if moreWork {
		ctx.State = StateExecute
	} else {
		ctx.State = StateComplete
	}
}
